### ISSUE TITLE
Support (or at least non-fatal handling) for git dependencies?

### ISSUE THREAD

**Issue by thedewi** [JamieMason/shrinkpack#19]
Git dependencies are causing fatal errors on my system.

My `npm-shrinkwrap.json` contains this github dependency entry:

```
"techan": {
  "version": "0.6.0",
  "from": "techan@git://github.com/andredumas/techan.js#f7d1489b61a2dd951036f9dc207d1c91339b00f9",
  "resolved": "git://github.com/andredumas/techan.js#f7d1489b61a2dd951036f9dc207d1c91339b00f9"
},
```

This derives from my `package.json` entry: `"techan": "andredumas/techan.js#0.6.0"`

Shrinkpack (or maybe it's npm's cache API) doesn't seem to know how to respond:

```
error adding techan@0.6.0 to npm cache: Error: Registry returned 404 for GET on https://registry.npmjs.org/techan
Please raise an issue at https://github.com/JamieMason/shrinkpack/issues

    TypeError: Cannot read property 'npm' of undefined
        at Object.addPackage (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\src\shrinkpack.js:24:33)
        at addToShrinkpack (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\index.js:117:27)
        at tryCatchReject (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:845:30)
        at runContinuation1 (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:804:4)
        at Fulfilled.when (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:592:4)
        at Pending.run (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:483:13)
        at Scheduler._drain (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:62:19)
        at Scheduler.drain (D:\dev\apps\GeonomicsCarbonSim\deploy\WebRoot\node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:27:9)
        at process._tickCallback (node.js:419:13)
```

**Comment by JamieMason** [comment]
Thanks for raising this, I'll get a fix sorted soon.

**Comment by JamieMason** [comment]
Got this working locally.

**Comment by DylanPiercey** [comment]
Will this fix scoped repos?

**Comment by JamieMason** [comment]
I've not (knowingly) used a scoped repo yet @DylanPiercey, do you have an example of one? I'll put it in the package.json I'm working with.

**Comment by JamieMason** [comment]
Version [0.5.0](https://github.com/JamieMason/shrinkpack/blob/master/CHANGELOG.md) has been released, please could you give it a try and update or close this issue? 

Thanks a lot @thedewi @DylanPiercey

**Comment by JamieMason** [comment]
Closing just as part of issue housekeeping, please re-open if needed.
