### ISSUE TITLE
TypeError: Cannot read property 'npm' of undefined

### ISSUE THREAD

**Issue by webuniverseio** [JamieMason/shrinkpack#23]
Hi, with version 0.6.0 I run into a following issue:

```
[SyntaxError: Unexpected end of input]
Please raise an issue at https://github.com/JamieMason/shrinkpack/issues

    TypeError: Cannot read property 'npm' of undefined
        at Object.addPackage (C:\dev\images\node_modules\shrinkpack\src\shrinkpack.js:24:31)
        at addToShrinkpack (C:\dev\images\node_modules\shrinkpack\index.js:115:23)
        at tryCatchReject (C:\dev\images\node_modules\when\lib\makePromise.js:845:30)
        at runContinuation1 (C:\dev\images\node_modules\when\lib\makePromise.js:804:4)
        at Fulfilled.when (C:\dev\images\node_modules\when\lib\makePromise.js:592:4)
        at Pending.run (C:\dev\images\node_modules\when\lib\makePromise.js:483:13)
        at Scheduler._drain (C:\dev\images\node_modules\when\lib\Scheduler.js:62:19)
        at Scheduler.drain (C:\dev\images\node_modules\when\lib\Scheduler.js:27:9)
        at doNTCallback0 (node.js:407:9)
        at process._tickCallback (node.js:336:13)
```

package.json:
[package.json.txt](https://github.com/JamieMason/shrinkpack/files/204602/package.json.txt)

**Comment by JamieMason** [comment]
Thanks @szarouski, 
There's quite a few different types of dependency formats in there so that'll be handy to test against. 

I think I'll need to remove `"esprima-fb": "15001.1001.0-dev-harmony-fb",` in my copy though as that looks like an internal server?

**Comment by webuniverseio** [comment]
Hi @JamieMason,
esprima-fb is installed from npm: https://www.npmjs.com/package/esprima-fb

**Comment by JamieMason** [comment]
Thanks a lot, I'll see if I can reproduce it and get back to you if not. Will most likely be Wednesday when I  next get chance.

**Comment by webuniverseio** [comment]
Meantime version 0.5.0 worked for me.

**Comment by DylanPiercey** [comment]
@JamieMason Wouldn't this be fixed since as of 0.5 "npm" is no longer a dependency?

**Comment by metachris** [comment]
I've experienced the same error with shrinkpack@0.6.0. Switched back to shrinkpack@0.5.0 and it works.

**Comment by JamieMason** [comment]
Thanks a lot for your help, this should be improved in [0.10.0](https://github.com/JamieMason/shrinkpack/releases/tag/0.10.0).
