### ISSUE TITLE
exec.js aborts on benign stderr messages from npm (in v0.6.0)

### ISSUE THREAD

**Issue by thedewi** [JamieMason/shrinkpack#26]
At `exec.js` line 11, stderr is checked and if non-empty, the command is considered to have failed.

But on my system (admittedly with an old npm), npm outputs a couple of benign lines to stderr whenever it refreshes its cache:

```
>npm view babel-plugin-proto-to-assign@1.0.4 --json > nul
npm http GET https://registry.npmjs.org/babel-plugin-proto-to-assign
npm http 304 https://registry.npmjs.org/babel-plugin-proto-to-assign

>npm view babel-plugin-proto-to-assign@1.0.4 --json > nul
```

The second time it is silent, but the first time worked fine too and should not be classified as having failed. If npm didn't return an error code, and you got valid json out of it, you probably don't need to worry about the contents of stderr for this command.

The error doesn't surface due to issues identified in #25 , and the process terminates with this message:

```
Please raise an issue at https://github.com/JamieMason/shrinkpack/issues

    TypeError: Cannot read property 'npm' of undefined
        at Object.addPackage (node_modules\shrinkpack\src\shrinkpack.js:25:31)
        at addToShrinkpack (node_modules\shrinkpack\index.js:119:23)
        at tryCatchReject (node_modules\shrinkpack\node_modules\when\lib\makePromise.js:845:30)
        at runContinuation1 (node_modules\shrinkpack\node_modules\when\lib\makePromise.js:804:4)
        at Fulfilled.when (node_modules\shrinkpack\node_modules\when\lib\makePromise.js:592:4)
        at Pending.run (node_modules\shrinkpack\node_modules\when\lib\makePromise.js:483:13)
        at Scheduler._drain (node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:62:19)
        at Scheduler.drain (node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:27:9)
        at process._tickCallback (node.js:419:13)
```

**Comment by hsrobflavorus** [comment]
I'm getting the same result:

`
Please raise an issue at https://github.com/JamieMason/shrinkpack/issues
    TypeError: Cannot read property 'npm' of undefined
        at Object.addPackage (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\src\shrinkpack.js:24:31)
        at addToShrinkpack (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\index.js:115:23)
        at tryCatchReject (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:845:30)
        at runContinuation1 (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:804:4)
        at Fulfilled.when (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:592:4)
        at Pending.run (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\makePromise.js:483:13)
        at Scheduler._drain (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:62:19)
        at Scheduler.drain (C:\Users\flavorus\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\when\lib\Scheduler.js:27:9)
        at nextTickCallbackWith0Args (node.js:433:9)
        at process._tickCallback (node.js:362:13)
`

**Comment by hsrobflavorus** [comment]
0.5.0 also seems to have this issue, but reverting to **0.4.1** works for now.

**Comment by JamieMason** [comment]
Thanks a lot @thedewi, picking this up now.
