### ISSUE TITLE
Can't run shrinkpack after upgrading from npm v4.6.1 to v5.0.3

### ISSUE THREAD

**Issue by nbarron16** [JamieMason/shrinkpack#86]
When I run 'shrinkpack' after upgrading to the lastest npm v.5.0.3:

Error: ! failed to read contents of npm cache
        at ChildProcess.onClose (C:\Users\\_Me_\AppData\Roaming\npm\node_modules\shrinkpack\src\analyse\read-npm-cache.js:40:25)
        at emitTwo (events.js:125:13)
        at ChildProcess.emit (events.js:213:7)
        at ChildProcess.cp.emit (C:\Users\\_Me_\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\cross-spawn\lib\enoent.js:40:29)
        at maybeClose (internal/child_process.js:897:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)

**Comment by JamieMason** [comment]
Please follow #83 for updates 👍

**Comment by b2yq** [comment]
I have the same error when i am trying to call 'shrinkpack'  even after update to npm 5.8.0, .
I am trying to accomplish tutorial from wiki on windows and I am still getting this error.
