### ISSUE TITLE
 Error: ! failed to read contents of npm cache

### ISSUE THREAD

**Issue by loujinliangdg** [JamieMason/shrinkpack#95]
$ shrinkpack
! Please raise an issue at https://github.com/JamieMason/shrinkpack/issues

    Error: ! failed to read contents of npm cache
        at ChildProcess.onClose (C:\Users\1\AppData\Roaming\npm\node_modules\shrinkpack\src\analyse\read-npm-cache.js:40:25)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at ChildProcess.cp.emit (C:\Users\1\AppData\Roaming\npm\node_modules\shrinkpack\node_modules\cross-spawn\lib\enoent.js:40:29)
        at maybeClose (internal/child_process.js:925:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by JamieMason** [comment]
[shrinkpack@0.19.0](https://github.com/JamieMason/shrinkpack/releases/tag/0.19.0) has been released which adds support for npm 7 and up.
